### ISSUE TITLE
Docs website issues (merge conflicts and 404s)

### ISSUE THREAD

**Issue by ryandeba** [imgly/pesdk-docs#14]
The master branch of this repo contains merge conflicts ([example](https://github.com/imgly/pesdk-docs/blob/7b5fc2e8de4ed7bbf789f4e97c95211b78099965/_apidocs/html5/v4/PhotoEditorSDK.UI.DesktopUI.Editor.html#L295)), which appear to be impacting the actual docs site (see this [screenshot](https://i.imgur.com/lT9UyaN.png) taken from https://docs.photoeditorsdk.com/apidocs/html5/v4/PhotoEditorSDK.UI.DesktopUI.Editor.html).

I don't know if it's related to the merge conflicts or not, but I'm also getting a lot of 404s when trying to navigate the docs ([example](https://docs.photoeditorsdk.com/apidocs/html5/v4/PhotoEditorSDK.UI.DesktopUI.html#identifier)).

Sorry if this is not the right place to reach out about this type of issue.

**Comment by dmbfm** [comment]
Thanks, @ryandeba, we'll look into this issue
