### ISSUE TITLE
Change download button icon to text (Android SDK)

### ISSUE THREAD

**Issue by taomanwai** [imgly/pesdk-docs#17]
If I wanna change the download button icon to text "Next" (in the pic, right bottom corner)

How can I do so ?

Thanks very much for help

![whatsapp image 2018-07-23 at 01 23 05](https://user-images.githubusercontent.com/5728843/43236818-91dc5a8a-90b9-11e8-9ee4-72d525a37a7b.jpeg)

**Comment by sascha** [comment]
Hi @taomanwai, please use https://support.photoeditorsdk.com to file a support request for the Android team.

**Comment by taomanwai** [comment]
Ok, thanks, filed ..
