### ISSUE TITLE
Broken controlOptions in Editor Setup

### ISSUE THREAD

**Issue by brainyfarm** [imgly/pesdk-docs#20]
It seems like the `controlOptions` is broken or does nothing or at least not when I try to use in limiting available options in each of the controls. Kindly take a look at the screenshots below for clarity.

**Code Sample** 
<img width="788" alt="screen shot 2019-01-29 at 8 14 56 pm" src="https://user-images.githubusercontent.com/11624587/51933888-9f244680-2402-11e9-8efd-c07590747a7a.png">

**Output (Focus):**
![screen shot 2019-01-29 at 8 15 54 pm](https://user-images.githubusercontent.com/11624587/51933934-bf540580-2402-11e9-97e2-9293d7ca8b49.png)

**Output (Adjustments):**
![screen shot 2019-01-29 at 8 16 58 pm](https://user-images.githubusercontent.com/11624587/51933990-e01c5b00-2402-11e9-8339-f01089bc1d0e.png)

**Device information:**
Browser: Google Chrome 71

PESDK Version: 4.13.3

**Comment by keiwando** [comment]
You're simply missing an "s". It should be `controlsOptions` instead of `controlOptions`.

**Comment by brainyfarm** [comment]
@keiwando,

Thanks for catching that. I must have made that mistake when moving pieces around. However, the issue is still unresolved.

While this works for `filter`, it doesn't work for `adjustments`.

**Updated Screenshots:**
Code:
<img width="744" alt="screen shot 2019-01-30 at 2 11 44 pm" src="https://user-images.githubusercontent.com/11624587/51983480-0ab8f300-2499-11e9-94c8-85b7cd4bb5b3.png">

Output Filter (Works as expected):
![screen shot 2019-01-30 at 2 12 40 pm](https://user-images.githubusercontent.com/11624587/51983533-2a501b80-2499-11e9-90ac-b2fecb2ee924.png)

Output Adjustment (Not working):
![screen shot 2019-01-30 at 2 13 49 pm](https://user-images.githubusercontent.com/11624587/51983569-4ce23480-2499-11e9-87c0-a7363dc3d795.png)

For the above ^^, only the `brightness, saturation, and contrast` options should exist?
I am following this portion of your documentation:
https://docs.photoeditorsdk.com/guides/html5/v4/features/adjustments

Question:
- Since I am using this with `UI.ReactUI`, could it be possible that this feature for `adjustments` only exists for `UI.DesktopUI`? (Your doc has no tab for `ReactUI`).

You can take a look at the test repository I am running this on. (I pushed the license since it is a trial)
https://github.com/brainyfarm/pesdk

**Comment by keiwando** [comment]
You are correct, the option is only available with the `DesktopUI`. The `ReactUI` simply ignores it. 

The ReactUI is outdated and will soon be deprecated. New features and customisation options are only being added to the DesktopUI.

**Comment by brainyfarm** [comment]
Thanks @keiwando 
I think it would be helpful if this is specified somewhere in that part of the documentation.

Besides, there is also an issue with the one of your getting started examples, I will bring that up as a new issue since that is beyond the scope of the current issue.
